### ISSUE TITLE
Week1. Stream과 Optional

### ISSUE THREAD

**Issue by ilgolf** [ilgolf/Java_Advenced_Study#1]
1. Stream에 존재하는 다양한 메서드
    1. 생성하기
    2. 가공하기
    3. 결과 만들기
2. 동작 순서
3. 성능 향상
4. 지연 처리
5. Null-safe Stream 생성
6. 줄여 쓰기

**Comment by ilgolf** [comment]
https://golf-dev.tistory.com/9

https://golf-dev.tistory.com/10

https://golf-dev.tistory.com/11

**Comment by qkrgnsgml** [comment]
https://blog.naver.com/spa8915/222639077086

https://blog.naver.com/spa8915/222643900686

**Comment by Tianea2160** [comment]
https://magical-fluorine-7a0.notion.site/1-ed3527d7f42b44aea5f295f827b30d78
https://magical-fluorine-7a0.notion.site/1-2-4aee13b87c474e7f9d0ee6ec16c01861

**Comment by doxxx93** [comment]
https://velog.io/@doxxx93/javaStudy1 (수정중)

**Comment by Raemerrr** [comment]
https://fish-hoodie-b32.notion.site/1-Stream-Optional-737c4b87753b443ea632ac0a6f51a239
(네이버 블로그는 MarkDown 지원이 안되네요 ㅠㅠ 노션에 정리해두고 나중에 옮기겠습니다~!)

**Comment by arsgsg1** [comment]
https://andrewyun.tistory.com/122
https://andrewyun.tistory.com/123

**Comment by wenodev** [comment]
stream 2번부터는 정리를 못했네요ㅜㅜ
부족한 부분 채워넣겠습니다!!

## stream
https://github.com/wenodev/CodeLife/blob/main/study/stream/stream.md

## optional
https://github.com/wenodev/CodeLife/blob/main/study/optional/optional.md

**Comment by yhkee0404** [comment]
https://github.com/yhkee0404/yhkee0404.github.io/blob/47d3d07aadc3d7b9ac1ea416e11613b835f4cde4/_posts/2022-02-10-package-java-util-stream.md
