### ISSUE TITLE
Week2. WrapperClass와 일급컬렉션

### ISSUE THREAD

**Issue by ilgolf** [ilgolf/Java_Advenced_Study#3]
1. 일급 컬렉션이란 ?

2. 일급 컬력션을 사용했을 때 이점 4가지

   - 비지니스에 종속적인 자료구조
   - 불변
   - 상태와 행위를 한 곳에서 관리
   - 이름이 있는 컬렉션
   
3. 일급 컬렉션의 단점

- 추가 : 단점에 대한 내용은 정리를 안해도 됩니다. 하지만 최소한 고민은 해보시기 바랍니다.

**Comment by Tianea2160** [comment]
https://magical-fluorine-7a0.notion.site/2-1-First-class-Collection-4c51d0423bee4cfb95d94e2d2e3c5c71
거의 다 적긴 했는데 일급컬렉션 단점부분만 좀 더 조사를 하고 있습니다.

**Comment by qkrgnsgml** [comment]
https://blog.naver.com/spa8915/222647418611
단점은 구글링 해도 안나오는것 같습니다

**Comment by arsgsg1** [comment]
https://andrewyun.tistory.com/125

**Comment by ilgolf** [comment]
https://golf-dev.tistory.com/12

https://golf-dev.tistory.com/14

**Comment by wenodev** [comment]
https://github.com/wenodev/CodeLife/blob/main/study/wrapper/FirstClassCollection.md
https://github.com/wenodev/CodeLife/blob/main/study/wrapper/wrapper.md

**Comment by Raemerrr** [comment]
https://blog.naver.com/rkdfoals/222650107892
