### ISSUE TITLE
Generic과 type Erasure, Enum 클래스

### ISSUE THREAD

**Issue by ilgolf** [ilgolf/Java_Advenced_Study#4]
금 주 주제는 이펙티브 자바를 참고해서 만들어졌습니다.

**Comment by Tianea2160** [comment]
generic
https://magical-fluorine-7a0.notion.site/3-1-Generic-type-erasure-and-Enum-class-3af220c14e1a495f8503da3bd8c299b4

enum
https://magical-fluorine-7a0.notion.site/3-2-Generic-type-erasure-and-Enum-class-12cb0e2500e14cdb8d4e5fcc73746141

**Comment by doxxx93** [comment]
generic
https://velog.io/@doxxx93/JAVA-Generics
type erasure
https://velog.io/@doxxx93/JAVAGeneric-Type-Erasure
enum
아직 공부중입니다 ㅠ

**Comment by ilgolf** [comment]
https://golf-dev.tistory.com/18

https://golf-dev.tistory.com/20

https://golf-dev.tistory.com/21

https://golf-dev.tistory.com/22

enum은 티스토리 오류로 보류

**Comment by qkrgnsgml** [comment]
https://blog.naver.com/spa8915/222655919916
https://blog.naver.com/spa8915/222656778610

Generic Enum에 대한 지식이 부족해서 내용이 부실한데 주말까지 좀 더 보충할 수 있으면 해오겠습니다.

**Comment by arsgsg1** [comment]
https://andrewyun.tistory.com/127
https://andrewyun.tistory.com/128

**Comment by Raemerrr** [comment]
Generic
https://fish-hoodie-b32.notion.site/3-Generic-type-Erasure-Enum-Class-1b5fc35cefe44856a1e3dcd9f609e493

Enum 좀 더 정리하겠습니다..!
