### ISSUE TITLE
7주차 : 직렬화 역직렬화 와 String 상수 풀

### ISSUE THREAD

**Issue by ilgolf** [ilgolf/Java_Advenced_Study#8]
1. Serializable
2. 날짜 형식 직렬화 전략
3. String = "" vs String = new String("")의 차이

**Comment by ilgolf** [comment]
https://golf-dev.tistory.com/26

**Comment by Tianea2160** [comment]
https://magical-fluorine-7a0.notion.site/7-1-String-7ab40c4ab8c44e6cbe728b46dbdf1151

**Comment by doxxx93** [comment]
https://celestial-airedale-6d2.notion.site/9ca79c311a354a7f84da76b75d1b7282
